### ISSUE TITLE
4.0.1 Does Not Resolve Modules Relative to Working Directory

### ISSUE THREAD

**Issue by ptefft-bizequity** [aws/aws-lambda-nodejs-runtime-interface-client#184]
## Dockerfile

I have a Dockerfile that has previously worked with RIC 3.3.0, following the conventions described in the [README for the 22.x branch](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/tree/nodejs22.x). It does not work on 4.0.1 I think because 4.0.1 fundamentally doesn't care about the current working directory anymore in favor of the `LAMBDA_TASK_ROOT` environment variable.

## 3.3.0 Behavior

In 3.3.0, (`nodejs22.x` branch), `bin/index.mjs` pulls the current working directory and uses that as the app root.

```
const appRoot = process.cwd();
const handler = process.argv[2];
  
console.log(`Executing '${handler}' in function directory '${appRoot}'`);
await run(appRoot, handler);
```

This works with the conventions on the 22.x README, which encourage me to put the handler at a relatively arbitrary `FUNCTION_DIR` that we also set as the working directory.

I wasn't able to find `LAMBDA_TASK_ROOT` in the source code on this branch.

## 4.0.1 Behavior

When moving to 4.0.1 (`nodejs24.x` branch), we get this error on AWS Lambda:

```
2026-01-27T19:25:52.402Z	-	ERROR	Init Error 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'lambda'\nRequire stack:\n- /function/node_modules/aws-lambda-ric/index.mjs",
    "name": "Runtime.ImportModuleError",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'lambda'",
        "Require stack:",
        "- /function/node_modules/aws-lambda-ric/index.mjs",
        "    at loadModule (file:///function/node_modules/aws-lambda-ric/index.mjs:575:13)",
        "    at async UserFunctionLoader.load (file:///function/node_modules/aws-lambda-ric/index.mjs:506:20)",
        "    at async createRuntime (file:///function/node_modules/aws-lambda-ric/index.mjs:1219:52)",
        "    at async ignition (file:///function/node_modules/aws-lambda-ric/index.mjs:1635:21)"
    ]
}
```

I don't see anything that tries to resolve the module against the working directory. It seems to rely only on the `LAMBDA_TASK_ROOT` environment variable.

## 24.x Docs

The README for the 24.x branch covers building a Lambda image using an arbitrary-ish base Docker image [here](https://github.com/aws/aws-lambda-nodejs-runtime-interface-client?tab=readme-ov-file#building-on-custom-linux-distributions).

These docs continue to use an arbitrary `FUNCTION_DIR` and don't seem to include any steps for copying handler code into the image, which leaves me with some questions.

## Questions

Is this behavior change expected/intentional?

If it is, I have the following questions as someone building an image from scratch, and we may want to clarify the README:
- As someone building an image, should I set a `LAMBDA_TASK_ROOT` variable pointing to where I put the handler module as the official images do (e.g. `public.ecr.aws/lambda/nodejs:22`)?
- Is it important or helpful for me to use `/var/task` as `LAMBDA_TASK_ROOT` or is it arbitrary?

**Comment by ptefft-bizequity** [comment]
Empirically, it looks like I can't establish a `LAMBDA_TASK_ROOT` environment variable in my Dockerfile that AWS Lambda will then actually adopt and use, so I need to use `/var/task` for this to work.

**Comment by Niek** [comment]
This took me *way* too long to figure out... `/var/task` seems to be the only solution right now.

**Comment by darklight3it** [comment]
Hey @ptefft-bizequity ,

thanks for your issue. That was a bug introduced from a recent refactoring. New version of the RIC will allow you to put the handler wherever you prefer.

**Comment by ptefft-bizequity** [comment]
Thank you, @darklight3it!

**Comment by ianyong** [comment]
Hey @darklight3it, thanks for fixing this issue. Is there any chance that the fix will be released anytime soon given that it's been merged for a couple of months already?
